Refactor Denormal and AltiVec and Delete CPU Detection code from CMake
thliebig/openEMS pull request #147
Opened 2024-08-29 19:29 UTC by biergaizi

## CMakeLists.txt: remove CPU architecture detection

The CPU architecture detection code was initially added during a IBM POWER port, and it was later extended to ARM too. But both are unnecessary, and was added due to unfamiliarity of the codebase by respective contributors. The CMake script does two things only: (1) If the CPU is non-x86, set the macro SSE_CORRECT_DENORMALS. (2) If the CPU is IBM POWER, set the macro NO_WARN_X86_INTRINSICS.

Both can be supported using C macros only, without the need to modify the CMake script. It does nothing but reducing the code portability by limiting supported CPUs to a hardcoded list. For example, fundamentally there's nothing to stop the codebase from working on RISC-V, but because nobody has allowlisted the CPU yet, it fails the check. In the future, as new users arrive, the check will be longer and longer for no good reason.

## FDTD: define NO_WARN_X86_INTRINSICS for ppc64le

On GCC, the SSE2 intrinsic header emmintrin.h supports AltiVec too when the macro NO_WARN_X86_INTRINSICS is set. Currently, this macro is set in the CMake build script, which introduces unnecessary CPU detection logic. This commit uses boost/predef.h, if BOOST_ARCH_PPC_64 and BOOST_ENDIAN_LITTLE_BYTE are set, the macro NO_WARN_X86_INTRINSICS will be defined. This allows us to remove the CPU detection logic from CMake.

Note that one still need to explicitly enable AltiVec support using suitable compiler flags, since we want to maximize the compatibility of a generic build. This is true for all architectures, including ARM (Neon) or PPC. It's also technically true for x86_64, it's just that SSE is mandatory so it's always enabled by default...

## FDTD: refactor denormal (subnormal) disabling logic

Currently, openEMS disables denormal (subnormal) numbers on x86 by calling _mm_setcsr(). To enable portability, a special macro SSE_CORRECT_DENORMALS was later introduced. The macro is set in CMake scripts by manually checking whether the current architecture is x86, if so, this code snippet is skipped.

To improve code clarity, this commit isolate the denormal disabling code into its own function Denormal::Disable(), it also uses boost/predef.h BOOST_ARCH_X86 is used to check the current architecture in a cross-platform way, instead of using CMake to set the original SSE_CORRECT_DENORMALS, which creates an unnecessary burden to detect and port the CMake scripts for each possible CPU.

2024-08-30 01:07 UTC, barracuda156 reviewed
I will need to run the build when I am back to the PowerMac, but the proposed change looks good, IMO. (See a question re Boost though.)

2024-08-30 01:07 UTC, barracuda156 commented on FDTD/engine_sse_compressed.cpp
> +#if defined(BOOST_ARCH_PPC_64) && defined(BOOST_ENDIAN_LITTLE_BYTE)
Can’t this just use standard macros? What is the benefit of pulling in Boost?
Both ppc64 and little-endianness can be detected without relying on Boost. (What Boost does itself is using the same macros anyway.)

2024-08-30 06:11 UTC, biergaizi commented on FDTD/engine_sse_compressed.cpp
> +#if defined(BOOST_ARCH_PPC_64) && defined(BOOST_ENDIAN_LITTLE_BYTE)
> What is the benefit of pulling in Boost?

As an experienced ppc64le packager, don't you realize that this project already depends on Boost? I'm not "pulling in Boost". If we already depend on it, why shouldn't we use it?

> Can’t this just use standard macros?

The main reason is readability.  This project must be compatible with MSVC and GCC, which uses different macros, so one needs to check at least 2 different macros to test whether it's x86, another two different macros to test whether it's x86-64. This is needed for the denormal floating point number function. If I got it right, they're `__x86_64__`, `_M_X64`, `_M_IX86`, and `__i386__` - checking whether it's MSVC is incorrect, since MSVC runs on ARM too.

With Boost, one can simply write `BOOST_ARCH_X86`.

> Both ppc64 and little-endianness can be detected without relying on Boost. 

For GCC on ppc64le, one can indeed use the GCC builtin macros without Boost. But the readers may find it's confusing if the detection for x86 uses Boost but the detection of ppc64le does not? So it's better to be consistent to use Boost consistently for PPC if we're using it for x86.

2024-08-30 07:04 UTC, barracuda156 commented on FDTD/engine_sse_compressed.cpp
> +#if defined(BOOST_ARCH_PPC_64) && defined(BOOST_ENDIAN_LITTLE_BYTE)
>  I'm not "pulling in Boost". If we already depend on it, why shouldn't we use it?

I was checking this from GH Mobile, so no, I did not at the moment :) 
No issues in using Boost headers then, I guess. I will update here once I run the build locally and close my PR it favor of yours.

2024-08-30 07:33 UTC, barracuda156 commented
@biergaizi Well, no, this actually fails to build. Boost 1.76:
```
[ 39%] Building CXX object CMakeFiles/openEMS.dir/FDTD/engine_sse_compressed.cpp.o
/opt/local/bin/ccache /opt/local/bin/g++-mp-14 -DGIT_VERSION=\"v0.0.36\" -DTIXML_USE_STL -Dkiss_fft_scalar=double -DopenEMS_EXPORTS -I/include -I/opt/local/include/CSXCAD -I/opt/local/include -I/opt/local/libexec/boost/1.76/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openEMS/openEMS/work/openEMS-1ccf0942477e9178b27f5e00dddd4d62bff78d29 -isystem /opt/local/include/vtk-9.3 -isystem /opt/local/include/vtk-9.3/vtknlohmannjson/include -pipe -I/opt/local/libexec/boost/1.76/include -Os -DNDEBUG -I/opt/local/libexec/boost/1.76/include -I/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0 -arch ppc -mmacosx-version-min=10.6 -fPIC -MD -MT CMakeFiles/openEMS.dir/FDTD/engine_sse_compressed.cpp.o -MF CMakeFiles/openEMS.dir/FDTD/engine_sse_compressed.cpp.o.d -o CMakeFiles/openEMS.dir/FDTD/engine_sse_compressed.cpp.o -c /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openEMS/openEMS/work/openEMS-1ccf0942477e9178b27f5e00dddd4d62bff78d29/FDTD/engine_sse_compressed.cpp
In file included from /opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/emmintrin.h:66,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openEMS/openEMS/work/openEMS-1ccf0942477e9178b27f5e00dddd4d62bff78d29/FDTD/engine_sse_compressed.cpp:24:
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h: In function '__m128 _mm_loadu_ps(const float*)':
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:122:11: error: 'vec_vsx_ld' was not declared in this scope; did you mean 'vec_vsld'?
  122 |   return (vec_vsx_ld(0, __P));
      |           ^~~~~~~~~~
      |           vec_vsld
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h: In function '__m128 _mm_sqrt_ss(__m128)':
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:342:18: error: '__builtin_vsx_xvsqrtsp' requires the '-mvsx' option
  342 |   __c = vec_sqrt (__a);
      |                  ^
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:342:18: note: overloaded builtin '__builtin_vec_sqrt' is implemented by builtin '__builtin_vsx_xvsqrtsp'
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h: In function '__m128 _mm_sqrt_ps(__m128)':
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:376:20: error: '__builtin_vsx_xvsqrtsp' requires the '-mvsx' option
  376 |   return (vec_sqrt ((__v4sf)__A));
      |                    ^
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:376:20: note: overloaded builtin '__builtin_vec_sqrt' is implemented by builtin '__builtin_vsx_xvsqrtsp'
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h: In function '__m64 _mm_cvtps_pi32(__m128)':
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:996:31: error: use of 'long long' in AltiVec types is invalid without '-mvsx'
  996 |   __vector unsigned long long __result;
      |                               ^~~~~~~~
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:999:47: error: use of 'long long' in AltiVec types is invalid without '-mvsx'
  999 |   __temp = (__v4sf) vec_splat ((__vector long long)__A, 0);
      |                                               ^~~~
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:999:31: error: '__builtin_vsx_xxspltd_2di' requires the '-mvsx' option
  999 |   __temp = (__v4sf) vec_splat ((__vector long long)__A, 0);
      |                               ^
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:999:31: note: overloaded builtin '__builtin_vec_splat' is implemented by builtin '__builtin_vsx_xxspltd_2di'
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:1000:24: error: '__builtin_vsx_xvrspic' requires the '-mvsx' option
 1000 |   __rounded = vec_rint (__temp);
      |                        ^
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:1000:24: note: overloaded builtin '__builtin_vec_rint' is implemented by builtin '__builtin_vsx_xvrspic'
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:1001:38: error: use of 'long long' in AltiVec types is invalid without '-mvsx'
 1001 |   __result = (__vector unsigned long long) vec_cts (__rounded, 0);
      |                                      ^~~~
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:1003:34: error: use of 'long long' in AltiVec types is invalid without '-mvsx'
 1003 |   return (__m64) ((__vector long long) __result)[0];
      |                                  ^~~~
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h: In function '__m64 _mm_cvttps_pi32(__m128)':
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:1054:31: error: use of 'long long' in AltiVec types is invalid without '-mvsx'
 1054 |   __vector unsigned long long __result;
      |                               ^~~~~~~~
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:1057:47: error: use of 'long long' in AltiVec types is invalid without '-mvsx'
 1057 |   __temp = (__v4sf) vec_splat ((__vector long long)__A, 0);
      |                                               ^~~~
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:1057:31: error: '__builtin_vsx_xxspltd_2di' requires the '-mvsx' option
 1057 |   __temp = (__v4sf) vec_splat ((__vector long long)__A, 0);
      |                               ^
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:1057:31: note: overloaded builtin '__builtin_vec_splat' is implemented by builtin '__builtin_vsx_xxspltd_2di'
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:1058:38: error: use of 'long long' in AltiVec types is invalid without '-mvsx'
 1058 |   __result = (__vector unsigned long long) vec_cts (__temp, 0);
      |                                      ^~~~
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:1060:34: error: use of 'long long' in AltiVec types is invalid without '-mvsx'
 1060 |   return (__m64) ((__vector long long) __result)[0];
      |                                  ^~~~
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h: In function '__m128 _mm_cvtpi32_ps(__m128, __m64)':
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:1111:57: error: use of 'long long' in AltiVec types is invalid without '-mvsx'
 1111 |   __vm1 = (__vector signed int) (__vector unsigned long long) {__B, __B};
      |                                                         ^~~~
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:1114:44: error: use of 'long long' in AltiVec types is invalid without '-mvsx'
 1114 |   return ((__m128) (__vector unsigned long long)
      |                                            ^~~~
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:1115:32: error: use of 'long long' in AltiVec types is invalid without '-mvsx'
 1115 |     { ((__vector unsigned long long)__vf1) [0],
      |                                ^~~~
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:1116:34: error: use of 'long long' in AltiVec types is invalid without '-mvsx'
 1116 |         ((__vector unsigned long long)__A) [1]});
      |                                  ^~~~
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h: In function '__m128 _mm_cvtpi16_ps(__m64)':
/opt/local/lib/gcc14/gcc/powerpc-apple-darwin10/14.2.0/include/xmmintrin.h:1133:59: error: use of 'long long' in AltiVec types is invalid without '-mvsx'
 1133 |   __vs8 = (__vect [...]

2024-08-30 07:43 UTC, barracuda156 requested changes
@biergaizi You should use `#if BOOST_ARCH_PPC_64` etc., not `#if defined`, because it is defined in any case, so the macro fails its purpose.

2024-08-30 07:47 UTC, barracuda156 commented
I.e., this works for me:
```
#include <boost/predef.h>
#if BOOST_ARCH_PPC_64 && BOOST_ENDIAN_LITTLE_BYTE
#define NO_WARN_X86_INTRINSICS
#include <emmintrin.h>
#endif
```
A version of macro with `#if defined` is always true, so it fails to work.

2024-08-30 10:11 UTC, biergaizi commented
Ah, I see, thanks for testing.

2024-08-30 10:22 UTC, biergaizi commented
I just force-pushed the fixed version, please test again.

2024-08-30 17:10 UTC, barracuda156 commented
Builds fine for me with ee742d5a1db840500c1ce76a148142a3efec5bdf 140e4175a7cf46d467b59472dc8850b60707324e 812ffb7ac58d84d78578857d2132918de66f239c b58effabf8546bddac86b2bae05ae8a58feb508e applied.

2024-09-16 17:55 UTC, thliebig commented on FDTD/engine_sse.cpp
> -	//_mm_setcsr( oldMXCSR ); // restore old setting
As far as I see it the "restore old setting" now never happens? I'm not sure it is really necessary as it is only active as long this process is running?

2024-10-11 22:28 UTC, biergaizi commented on FDTD/engine_sse.cpp
> -	//_mm_setcsr( oldMXCSR ); // restore old setting
This line of code is dead code, it has been commented out since forever ago (perhaps during debugging, do you remember anything?), so I decided to remove it. Over the years, nobody reported any problem, because as you said, as long as the openEMS process is still running whether or not the settings are restored is a non-issue.

2024-11-09 11:40 UTC, merged